from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
import io
import fitz  # PyMuPDF
import re    # Python's built-in tool for cleaning text

app = FastAPI()

# Allow React (running on port 5173) to talk to this Python Backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# DATA MODELS (with correct indentation!)
# ==========================================
class Definition(BaseModel):
    term: str
    definition: str

class NoteResponse(BaseModel):
    title: str
    summaryPoints: List[str]
    keyConcepts: List[str]
    definitions: List[Definition]

class TextInput(BaseModel):
    text: str

class ExtractResponse(BaseModel):
    text: str
    wordCount: int

# ==========================================
# AI LOGIC PLACEHOLDER
# ==========================================
def process_content_with_ai(content: str) -> NoteResponse:
    return NoteResponse(
        title="Generated Study Notes",
        summaryPoints=[
            "This summary was generated by the Python Backend.",
            "The system received your input content successfully."
        ],
        keyConcepts=["Backend Connected", "FastAPI", "React Integration"],
        definitions=[
            {"term": "PyMuPDF", "definition": "A smart library used to extract text without weird letter spacing."},
            {"term": "Regex", "definition": "Used to clean up messy formatting and make the font/text uniform."}
        ]
    )

# ==========================================
# ENDPOINTS
# ==========================================

@app.post("/generate-from-text", response_model=NoteResponse)
async def generate_text(data: TextInput):
    # Clean pasted text
    cleaned_text = re.sub(r'\s+', ' ', data.text).strip()
    return process_content_with_ai(cleaned_text)

@app.post("/generate-from-pdf", response_model=NoteResponse)
async def generate_from_pdf(file: UploadFile = File(...)):
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="File must be a PDF")
    
    try:
        # Read the uploaded PDF file
        contents = await file.read()
        
        # Open PDF with PyMuPDF
        pdf_document = fitz.open(stream=contents, filetype="pdf")
        
        raw_text = ""
        for page_num in range(len(pdf_document)):
            page = pdf_document.load_page(page_num)
            raw_text += page.get_text() + " "
            
        # Clean text formatting
        cleaned_text = re.sub(r'\s+', ' ', raw_text)
        cleaned_text = re.sub(r'(?<=\b[a-zA-Z])\s(?=[a-zA-Z]\b)', '', cleaned_text)
        cleaned_text = cleaned_text.strip()
        
        # Print to terminal
        print("\n" + "="*50)
        print(f"--- CLEANED TEXT FROM: {file.filename} ---")
        print("="*50)
        print(cleaned_text)  
        print("="*50 + "\n")

        if not cleaned_text:
            raise HTTPException(status_code=400, detail="Could not extract text from this PDF.")

        # Send to AI
        return process_content_with_ai(cleaned_text)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing PDF: {str(e)}")

@app.post("/extract-pdf", response_model=ExtractResponse)
async def extract_pdf_only(file: UploadFile = File(...)):
    """New endpoint for the Preview Page to fetch text before generating notes"""
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="File must be a PDF")
    
    try:
        contents = await file.read()
        pdf_document = fitz.open(stream=contents, filetype="pdf")
        
        raw_text = ""
        for page_num in range(len(pdf_document)):
            page = pdf_document.load_page(page_num)
            raw_text += page.get_text() + " "
            
        # Clean text formatting
        cleaned_text = re.sub(r'\s+', ' ', raw_text)
        cleaned_text = re.sub(r'(?<=\b[a-zA-Z])\s(?=[a-zA-Z]\b)', '', cleaned_text).strip()

        if not cleaned_text:
            raise HTTPException(status_code=400, detail="No text found.")

        # Count words
        word_count = len(cleaned_text.split())
        
        return ExtractResponse(text=cleaned_text, wordCount=word_count)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error extracting PDF: {str(e)}")